version: "3.9"
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "congratulator_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"